---
platform: linux

inputs:
- name: greenplum-database-release
- name: gpdb_rpm_installer
- name: gpdb_rpm_oss_installer
  optional: true
- name: previous-5.25.0-release
  optional: true
- name: previous-5.28.4-release
  optional: true
- name: previous-6.2.1-release
  optional: true
- name: previous-6.20.0-release
  optional: true
- name: previous-7.0.0-release
  optional: true
- name: inspec

run:
  path: greenplum-database-release/ci/concourse/scripts/test-functionality-rpm.bash

params:
  PLATFORM:
  GPDB_MAJOR_VERSION:
